[project]
name = "foxypack-youtube-pytubefix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "foxy-entities>=0.0.3",
    "foxypack",
    "pytubefix>=10.10.1",
    "regex>=2026.6.28",
]

[tool.uv.sources]
foxypack = { git = "ssh://git@github.com/ShapDi/foxypack.git" }
